/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUserDialog: typeof import('./src/components/AddUserDialog/src/AddUserDialog.vue')['default']
    Button: typeof import('./src/components/Button/src/Button.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/src/components/ColumnSetting.vue')['default']
    ConfigGlobal: typeof import('./src/components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/ConfirmDeleteDialog/src/ConfirmDeleteDialog.vue')['default']
    ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default']
    CreateEditDialog: typeof import('./src/components/CreateEditDialog/src/CreateEditDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormDialog: typeof import('./src/components/FormDialog/src/FormDialog.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    InviteDialog: typeof import('./src/components/InviteDialog/src/InviteDialog.vue')['default']
    Logo: typeof import('./src/components/Logo/src/Logo.vue')['default']
    ManagementList: typeof import('./src/components/ManagementList/src/ManagementList.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    OperationDialog: typeof import('./src/components/OperationDialog/src/OperationDialog.vue')['default']
    Pagination: typeof import('./src/components/Pagination/src/Pagination.vue')['default']
    Permission: typeof import('./src/components/Permission/src/Permission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TableActions: typeof import('./src/components/Table/src/components/TableActions.vue')['default']
    TableFilterPopover: typeof import('./src/components/TableFilterPopover/src/TableFilterPopover.vue')['default']
    TableToolbar: typeof import('./src/components/TableToolbar/src/TableToolbar.vue')['default']
    UniversalFormDialog: typeof import('./src/components/UniversalFormDialog/src/UniversalFormDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
